### ISSUE TITLE
Game detail - When user clicks on games plateforms or genre it should be redirect to the filtered listing page

### ISSUE THREAD

**Issue by CamilleLetang** [Games-of-Switzerland/gos-website#39] opened 2020-11-07 09:52 UTC
To reproduce:
1. go on : https://staging-gos.museebolo.ch/games/farming-simulator-14
2. Click ok: 
<img width="1405" alt="Capture d’écran 2020-11-07 à 10 49 07" src="https://user-images.githubusercontent.com/27284929/98437992-44e00b80-20e7-11eb-9dda-d87fd51f5d5f.png">
3. You will land here: https://staging-gos.museebolo.ch/games/ba3b0058-5ea2-4367-8edd-b9629fe7e11a
<img width="1439" alt="Capture d’écran 2020-11-07 à 10 49 42" src="https://user-images.githubusercontent.com/27284929/98437985-3db8fd80-20e7-11eb-8c58-9ee0c181bded.png">

For this example, you should land here: https://staging-gos.museebolo.ch/?platforms[]=ps_vita

**Comment by tonifisler** [comment] 2020-11-08 23:47
duplicate of #25

**Closed** 2022-03-14 13:10 UTC
Labels: bug
